#!/usr/bin/env sh

# Examples:
# https://github.com/koekeishiya/dotfiles/blob/master/yabai/yabairc
# https://gitlab.com/TamasBarta/dotfiles/-/blob/master/yabai/.config/yabai/yabairc

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# mission-control desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label work
yabai -m space 4 --label notes
yabai -m space 5 --label comms
yabai -m space 6 --label media
yabai -m space 7 --label tmp1
yabai -m space 8 --label tmp2

# window rules
# yabai -m rule --add app="Firefox.*$" space=web
yabai -m rule --add app="^Notion$" space=notes
yabai -m rule --add app="^Spotify$" space=media

# don't manage the following applications/windows
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" title="^.* Info$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^1Password.*$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --add app="^Cisco Webex Meetings$" title="^Preferences$" manage=off
yabai -m rule --add app="^GIMP-.*$" title="^Export Image$" manage=off
yabai -m rule --add app="^GIMP-.*$" title="^Scale Image$" manage=off
yabai -m rule --add app="^GIMP-.*$" title="^Set Image Canvas Size$" manage=off
yabai -m rule --add app="^Code42$" title="^Code42$" manage=off

# https://github.com/koekeishiya/yabai/issues/384#issuecomment-753514066
# https://github.com/koekeishiya/yabai/issues/350
yabai -m rule --add app="^Firefox.*$" title="^Opening .*$" manage=off

echo "yabai configuration loaded.."
